# base config
baseURL = "http://example.org/" 
defaultContentLanguage = "zh-cn" # site language, use to select i18n file
hasCJKLanguage = true 
languageCode = "zh-CN" # html language
theme = "next-theme" 
title = "Example Title" # site title

[outputs]
  home = ["HTML", "RSS", "JSON"] # 主要添加了 json 解析配置用于输出用于搜索的索引文件

[params]
author = "Example" 
avatar = ""  # 头像
links_title = "欢迎访问" # welcome
since = 2020 
subtitle = "hello world" # site subtitle

  # [[params.social]] # social: icon + text
  # icon = "fab fa-github"
  # name = "GitHub"
  # url = ""
  # [[params.links]] # link: only text
  # name = ""
  # url = ""
  # [[params.links]]
  # name = ""
  # url = ""
  [params.github_banner]
  enable = true
  permalink = ""

[menu] # menu, if not use just to comment
  [[menu.main]]
  name = "home"
  pre = "<i class='fa fa-home fa-fw'></i>"
  url = "/"
  weight = -100
  [[menu.main]]
  name = "about"
  pre = "<i class='fa fa fa-user fa-fw'></i>"
  url = "/about/"
  weight = -90
  [[menu.main]]
  identifier = "tags"
  name = "tags"
  pre = "<i class='fa fa-tags fa-fw'></i>"
  url = "/tags/"
  weight = -80
  [[menu.main]]
  identifier = "categories"
  name = "categories"
  pre = "<i class='fa fa-th fa-fw'></i>"
  url = "/categories/"
  weight = -70
  [[menu.main]]
  identifier = "archives"
  name = "archives"
  pre = "<i class='fa fa-archive fa-fw'></i>"
  url = "/posts/"
  weight = 20

[markup]
  [markup.tableOfContents]
  endLevel = 4
  startLevel = 1
  [markup.highlight]
  style = "friendly"
